name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: docker

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ailchishin/practice:tagname

    - name: log in to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_password }}

    - name: push docker image
      run: docker push ${{ secrets.dockerhub_username }}/practice:tagname

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ailchishin/practice:tagname
          docker stop my_container || true
          docker rm my_container || true
          docker run -d -p 80:8080 --name my_container ailchishin/practice:tagname


