name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: |
          echo "Pulling Docker Image..."
          ssh -i ~/.ssh/id_rsa ec2-user@52.23.179.202 "docker pull ailchishin/practice:tagname"

          echo "Running Docker Container..."
          ssh -i ~/.ssh/id_rsa ec2-user@52.23.179.202 "docker run -d -p 8080:8080 --name container-name ailchishin/practice:tagname"


  
       


